services:
  mysql:
    image: mysql:8.0
    container_name: security-container
    restart: always
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: authdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpw
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: