### 전체 사용자 목록 조회
GET http://localhost:8080/api/users
Accept: application/json

###

### 단일 사용자 조회 (ID: 1)
GET http://localhost:8080/api/users/1
Accept: application/json

###

### 사용자 삭제 (ID: 1)
DELETE http://localhost:8080/api/admin/1
