spring:
  datasource:
    url: jdbc:mysql://localhost:3312/authdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testuser
    password: testpw
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org.springframework.security: debug
      com.spring.study.springsecurity.security: TRACE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
jwt:
  secret:
    key: RGV2U2VjS2V5MjAyNXhZekdoVHE3THBSOXZGMXVNNE5uQzBwdXBweWNhdGdiaXJkZ2lhbnRwYW5kYW
  access:
    expiration: 3600000 # 1??
  refresh:
    expiration: 604800000 # 7?

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600
