spring:
  datasource:
    url: jdbc:mysql://localhost:3312/authdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testuser
    password: testpw
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org.springframework.security: debug


app:
  jwt:
    secret: yourSecretKeyHereMakeItLongAndComplexForSecurity123!@#$%^&*()
    expiration: 86400000
    header: Authorization


cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600
